queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>1"

pull_request_rules:
  - name: automerge to the base branch with label automerge and branch protection passing
    conditions:
      - "#approved-reviews-by>1"
      - base=main
      - label=automerge
    actions:
      queue:
        name: default
      merge:
        method: squash
        strict: true
        commit_message: title+body
  - name: backport patches to v0.8.x branch
    conditions:
      - base=main
      - label=backport/0.8.x
    actions:
      backport:
        branches:
          - release/v0.8.x
  - name: backport patches to v0.7.x branch
    conditions:
      - base=main
      - label=backport/0.7.x
    actions:
      backport:
        branches:
          - release/v0.7.x
