pull_request_rules:
  - name: automerge to base branch with label automerge and branch protection passing
    conditions:
      - "#approved-reviews-by>1"
      - base=main
      - label=automerge
    actions:
      merge:
        method: squash
        strict: true
