apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=../networks/local/ethermintnode/Dockerfile", # TODO: how to get this pass as a variable
           "--build-arg=-t ethermintd/node",
           "--context=dir://workspace", # TODO same thing
           "--no-push"]
    volumeMounts:
      - name: dockerfile-storage
        mountPath: /workspace # TODO same thing
  restartPolicy: Never
  volumes:
    - name: dockerfile-storage
      persistentVolumeClaim:
        claimName: dockerfile-claim