/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { TestChainID } from "../TestChainID";

export class TestChainID__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<TestChainID> {
    return super.deploy(overrides || {}) as Promise<TestChainID>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): TestChainID {
    return super.attach(address) as TestChainID;
  }
  connect(signer: Signer): TestChainID__factory {
    return super.connect(signer) as TestChainID__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TestChainID {
    return new Contract(address, _abi, signerOrProvider) as TestChainID;
  }
}

const _abi = [
  {
    inputs: [],
    name: "currentChainID",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50607680601d6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063b179e1e714602d575b600080fd5b4660405190815260200160405180910390f3fea26469706673582212200ab2fe344c609c675dfb009b4277fc1892ddd3c5247d73679f7b2d237318102d64736f6c634300080a0033";
