name: Format
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: technote-space/get-diff-action@v5
        id: git_diff
        with:
          SUFFIX_FILTER: |
            .go
            .mod
            .sum
      - run: |
          make format
        if: "env.GIT_DIFF != ''"
