name: "Pull Request Labeler"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
