name: Run Gosec
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2.4.0
      - name: Run Gosec Security Scanner
        uses: informalsystems/gosec@master
        with:
          args: ./...
